CS416/GoGoLimo/FinalProject/src/java/edu/ccsu/beans/LogIn.java
package edu.ccsu.beans;

import java.io.Serializable;
import javax.faces.bean.ManagedBean;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
 
@ManagedBean
public class LogIn implements Serializable
{
    
    private Integer id;
    public String customerID="";
    private String password="";   
      
    public  LogIn()
    {
       
       
 }

    public String getCustomerID()
    {
       return customerID;
    }
    
    public void setCustomerID(String customerID)
    {
        this.customerID = customerID;
    }
    
    public String getPassword()
    {
        return password;
    }
    
    public void setPassword(String password)
    {
        this.password = password;
    }
}

CS416/GoGoLimo/FinalProject/src/java/edu/ccsu/beans/ReserveDropBean.java
/*
 * Bean for drop off reservations
 * @author Cameron
 */
package edu.ccsu.beans;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Resource;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.PersistenceUnit;
import javax.persistence.Query;
import javax.transaction.UserTransaction;

@ManagedBean
@Named
public class ReserveDropBean {
    @PersistenceUnit(unitName = "FinalProjectPU")
    private EntityManagerFactory entityManagerFactory;
    @Resource
    private UserTransaction userTransaction;
    @ManagedProperty(value = "#{reservationDrop}")
    private ReservationDrop reservationDrop;
    
    public ReservationDrop  getReservationDrop() {
        return reservationDrop;
    }
    public void setReservationDrop(ReservationDrop reservationDrop){
        this.reservationDrop = reservationDrop;
    }    
    
    /*Saving to database*/
    public String saveInfo() 
    {
        String returnValue = "error";
        try {
            userTransaction.begin();
            EntityManager em = entityManagerFactory.createEntityManager();
            em.persist(reservationDrop);
            userTransaction.commit();
            em.close();
            returnValue = "DropConfirm";
        } catch (Exception e) {
            e.printStackTrace();
        }
        return returnValue;
    }

    /*Searching by email*/
    public List getMatchingEmail() {
        List<ReservationDrop> reservationDrops = new ArrayList();
        EntityManager entityManager = entityManagerFactory.createEntityManager();
        String selectSQL = "select r from ReservationDrop r where r.email like :email";
        try {
            Query selectQuery = entityManager.createQuery(selectSQL);
            selectQuery.setParameter("email", reservationDrop.getEmail() + "%");
            reservationDrops = selectQuery.getResultList();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return reservationDrops;
    }
    
    /*Searching by reservation ID*/
    public ReservationDrop getMatchingId() {        
        List<ReservationDrop> reservationDrops = new ArrayList();
        EntityManager entityManager = entityManagerFactory.createEntityManager();
        String selectSQL = "select r from ReservationDrop r where r.id like :id";
        try {
            Query selectQuery = entityManager.createQuery(selectSQL);
            selectQuery.setParameter("id", reservationDrop.getId() + "%");
            reservationDrops = selectQuery.getResultList();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return reservationDrops.get(0);
    }
    
    /*Deletes a reseravation.*/
    public String delete(Integer i) {
        String returnValue = "error";
        String selectSQL = "delete from RESERVATIONDROP id = :i";
        try {
            userTransaction.begin();
            EntityManager em = entityManagerFactory.createEntityManager();
            Query selectQuery = em.createQuery(selectSQL);
            userTransaction.commit();
            em.close();
            returnValue = "DropDeleteConfirm";
        } catch (Exception e) {
            e.printStackTrace();
        }
        return returnValue;
    }
    
    /*Update a reservation.*/
    public String update(String airport, String ampm, int day, int month,
                         int year, int hour, int minute) {
        String returnValue = "error";
        try {
            userTransaction.begin();
            EntityManager em = entityManagerFactory.createEntityManager();
            reservationDrop.setAirport(airport);
            reservationDrop.setAmpm(ampm);
            reservationDrop.setrDay(day);
            reservationDrop.setrMonth(month);
            reservationDrop.setrYear(year);
            reservationDrop.setrHour(hour);
            reservationDrop.setrMinute(minute);
            userTransaction.commit();
            em.close();
            returnValue = "DropUpdateConfirm";
        } catch (Exception e) {
            e.printStackTrace();
        }                
        return returnValue;
    }    
}

CS416/GoGoLimo/FinalProject/src/java/edu/ccsu/beans/SignUp.java
package edu.ccsu.beans;

import java.io.Serializable;
import javax.faces.bean.ManagedBean;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
 
@Entity
@ManagedBean
public class SignUp implements Serializable
{
    @Id
    @GeneratedValue
    private Integer id;
    private String customerID="";
    private String password="";   
      
    public SignUp()
    {
        
    }
    
    public String getCustomerID()
    {
        return customerID;
    }
    
    public void setCustomerID(String customerID)
    {
        this.customerID = customerID;
    }
    
    public String getPassword()
    {
        return password;
    }
    
    public void setPassword(String password)
    {
        this.password = password;
    }
}

CS416/GoGoLimo/FinalProject/src/java/edu/ccsu/controllers/LogInController.java
package edu.ccsu.controllers;


import edu.ccsu.beans.SignUp;
import edu.ccsu.beans.LogIn;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.Resource;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.PersistenceUnit;
import javax.persistence.Query;
import javax.transaction.UserTransaction;


@ManagedBean
public class LogInController 
{

    @PersistenceUnit(unitName = "FinalProjectPU")
    private EntityManagerFactory entityManagerFactory;
    @Resource
    private UserTransaction userTransaction;
    @ManagedProperty(value = "#{signUp}")
    private SignUp signUp;
    @ManagedProperty(value = "#{logIn}")
    private LogIn logIn;
    
    public String getMatchingIDPS() 
    { 
        String targetpage="Navigation01";
        String errorpage="Error";
        List<SignUp> customers = new ArrayList();
        EntityManager entityManager = entityManagerFactory.createEntityManager();
        String selectSQL = "select s from SignUp s where s.customerID like :customerID";
        try {
            Query selectQuery = entityManager.createQuery(selectSQL);
            selectQuery.setParameter("customerID", signUp.getCustomerID()+ "%");
            customers = selectQuery.getResultList();
        } catch (Exception e) {
            e.printStackTrace();
        }
        if (customers.contains(logIn.customerID))  
        return errorpage;
        else
        return targetpage;
        
    }
    public SignUp getSignUp() {
        return signUp;
    }

    public void setSignUp(SignUp signUp) {
        this.signUp = signUp;
    }
    
    public LogIn getLogIn()
    {
        return logIn;
    }  
    
    public void setLogIn(LogIn logIn)
    {
        this.logIn = logIn;
    }

}


CS416/GoGoLimo/FinalProject/web/CustomerSearch.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>GoGo Limo</title>
        <style type="text/css">
        h2 {color: white; background-color: #1db140}
        </style>
        <link href="main.css" rel="stylesheet" type="text/css" />
    </h:head>
    <h:body>
       <div id="outer">
           <h1>
               <a href="Login.xhtml">
                   <h:graphicImage url="/images/LimoLogo.jpg" alt="GoGo Limo"/>
               </a>
           </h1>
       </div>
 
      <div id="inner">
          <h2>Search</h2>
    <h:form>
    <h:panelGrid columns="2">
    <h:outputText value="Enter First Name"/>
    <h:inputText id="first" value="#{customer.firstName}">
    <f:ajax event="keyup" execute="last" render="datatable"/>
    </h:inputText>
    <h:outputText value="Enter Last Name"/>
    <h:inputText id="last" value="#{customer.lastName}">
    <f:ajax event="keyup" execute="first" render="datatable"/>
    </h:inputText>
    </h:panelGrid>
    <br/>
    <h:dataTable id="datatable" value="#{customerSave.matchingName}" var="item" border="3" cellpadding="2" cellspacing="2">
    <h:column>
    <f:facet name="header">
    <h:outputText value="First Name" />
    </f:facet>
    <h:outputText value="#{item.firstName}" ></h:outputText>
    </h:column>
    <h:column>
    <f:facet name="header">
    <h:outputText value="Last Name"/>
    </f:facet>
    <h:outputText value="#{item.lastName}"></h:outputText>
    </h:column>
    <h:column>
    <f:facet name="header">
    <h:outputText value="Email"/>
    </f:facet>
    <h:outputText value="#{item.email}"></h:outputText>
    </h:column>
    </h:dataTable>
    </h:form>
  </div>
    </h:body>
</html>

CS416/GoGoLimo/FinalProject/web/DropDeleteConfirm.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html 
    xmlns="http://www.w3.org/1999/xhtml"  
    xmlns:h="http://java.sun.com/jsf/html"  
    xmlns:f="http://java.sun.com/jsf/core">  
    <h:head>
      <title>GoGo Limo</title>
      <style type="text/css">
        h2 {color: white; background-color: #1db140}
      </style>
      <link href="main.css" rel="stylesheet" type="text/css" />
    </h:head>
    
    <h:body>
      <div id="outer">
        <h1>
          <a href="Login.xhtml">
            <h:graphicImage url="/images/LimoLogo.jpg" alt="GoGo Limo"/>
          </a>
        </h1>
      </div>

      <div id="inner">
        <h2>Your reservation has been deleted.</h2>
        <p><h:outputLink value="Navigation01.xhtml">Return to Navigation Screen</h:outputLink></p>
      </div>
    </h:body>
</html>

CS416/GoGoLimo/FinalProject/web/DropReview.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>GoGo Limo</title>
        <style type="text/css">
        h2 {color: white; background-color: #1db140}
        </style>
        <link href="main.css" rel="stylesheet" type="text/css" />
    </h:head>
    <h:body>
       <div id="outer">
           <h1>
               <a href="Login.xhtml">
                   <h:graphicImage url="/images/LimoLogo.jpg" alt="GoGo Limo"/>
               </a>
           </h1>
       </div>
 
      <div id="inner">
          <h2>Review your order</h2>
        <!--Show user reservation information-->
        <p><b><u>My Reservation</u></b></p>
        <!--Display airport and whether it is pick up or drop off-->
        <h:outputText value ="#{reservationDrop.toString()}" /><br/>
        
        <!--Submit product selection button-->
        <h:form>
            <h:commandButton value = "Submit"
                             type = "submit"
                             action = "#{reserveDropBean.saveInfo}" />
        </h:form>
      </div>
    </h:body>
    
</html>

CS416/GoGoLimo/FinalProject/web/DropSearch.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>GoGo Limo</title>
        <style type="text/css">
        h2 {color: white; background-color: #1db140}
        </style>
        <link href="main.css" rel="stylesheet" type="text/css" />
    </h:head>
    
    <h:body>
      <div id="outer">
          <h1>
              <a href="Login.xhtml">
                  <h:graphicImage url="/images/LimoLogo.jpg" alt="GoGo Limo"/>
              </a>
          </h1>
      </div>
 
      <div id="inner"> 
      <h2>Reservation Drop Off Info Search</h2>
      <h:form>
        <h:panelGrid columns="2">
            <h:outputText value="Confirm email "/>
            <h:inputText id="email" value="#{reservationDrop.email}">
                <f:ajax event="keyup" execute="last" render="datatable"/>
            </h:inputText>    
        </h:panelGrid> <br/>
        <h:dataTable id="datatable" value="#{reserveDropBean.matchingEmail}"
                var="item" border="3" cellpadding="2" cellspacing="2">
            <h:column>
                <f:facet name="header">
                    <h:outputText value="Email"/>
                </f:facet> 
                <h:outputText value="#{item.email}"></h:outputText>
            </h:column>
        
            <h:column>
                <f:facet name="header">
                    <h:outputText value=" - - - - - Reservation Information - - - - - " />
                </f:facet> 
                <h:outputText value="#{item.toString()}" ></h:outputText>
            </h:column>
    
            <h:column>
              <f:facet name="header">
                <h:outputText value="Drop-off ID" />
              </f:facet>
            <h:outputText value="#{item.id}" ></h:outputText>
          </h:column>
        </h:dataTable>
      </h:form>
    </div>
        
    <h3>Make Changes to Drop off Schedule</h3>
      <table>  
        <tr>  
          <td><h:outputLink value="DropDelete.xhtml"> Delete a drop off Reservation </h:outputLink></td>
          <td></td>
          <td><h:outputLink value="DropUpdate.xhtml"> Update a drop off Reservation </h:outputLink></td>  
        </tr>  
      </table>
    </h:body>
</html>

CS416/GoGoLimo/FinalProject/web/DropUpdate.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>GoGo Limo</title>
        <style type="text/css">
        h2 {color: white; background-color: #1db140}
        </style>
        <link href="main.css" rel="stylesheet" type="text/css" />
    </h:head>
    <h:body>
       <div id="outer">
           <h1>
               <a href="Login.xhtml">
                   <h:graphicImage url="/images/LimoLogo.jpg" alt="GoGo Limo"/>
               </a>
           </h1>
       </div>
        
        <div id = "inner">
          <h2>Make changes to your drop-off reservation.</h2>
          <p><b>Select reservation number</b></p>
          <h:inputText label="id" value="#{reservationPickUp.id}" id="thisId" required="true" />
          <p><b>Select an airport</b></p>
          
            <h:selectOneRadio value="#{reservationDrop.airport}">
                <f:selectItem   itemValue = "JFK"
                                itemLabel = "NYC - JFK Airport" />
                <f:selectItem   itemValue = "LaGuardia"
                                itemLabel = "NYC - Laguardua Airport" />
                <f:selectItem   itemValue = "Bradley"
                                itemLabel = "CT - Bradley International" />
            </h:selectOneRadio> <br/>
            <!--Date of reservation-->
            <p><b>Select a date</b></p>
            <!--Day-->
            Day:
            <h:selectOneMenu value = "#{reservationDrop.rDay}">
                <f:selectItem itemValue = "1" itemLabel = "1" />
                <f:selectItem itemValue = "2" itemLabel = "2" />
                <f:selectItem itemValue = "3" itemLabel = "3" />
                <f:selectItem itemValue = "4" itemLabel = "4" />
                <f:selectItem itemValue = "5" itemLabel = "5" />
                <f:selectItem itemValue = "6" itemLabel = "6" />
                <f:selectItem itemValue = "7" itemLabel = "7" />
                <f:selectItem itemValue = "8" itemLabel = "8" />
                <f:selectItem itemValue = "9" itemLabel = "9" />
                <f:selectItem itemValue = "10" itemLabel = "10" />
                <f:selectItem itemValue = "11" itemLabel = "11" />
                <f:selectItem itemValue = "12" itemLabel = "12" />
                <f:selectItem itemValue = "13" itemLabel = "13" />
                <f:selectItem itemValue = "14" itemLabel = "14" />
                <f:selectItem itemValue = "15" itemLabel = "15" />
                <f:selectItem itemValue = "16" itemLabel = "16" />
                <f:selectItem itemValue = "17" itemLabel = "17" />
                <f:selectItem itemValue = "18" itemLabel = "18" />
                <f:selectItem itemValue = "19" itemLabel = "19" />
                <f:selectItem itemValue = "20" itemLabel = "20" />
                <f:selectItem itemValue = "21" itemLabel = "21" />
                <f:selectItem itemValue = "22" itemLabel = "22" />
                <f:selectItem itemValue = "23" itemLabel = "23" />
                <f:selectItem itemValue = "24" itemLabel = "24" />
                <f:selectItem itemValue = "25" itemLabel = "25" />
                <f:selectItem itemValue = "26" itemLabel = "26" />
                <f:selectItem itemValue = "27" itemLabel = "27" />
                <f:selectItem itemValue = "28" itemLabel = "28" />
                <f:selectItem itemValue = "29" itemLabel = "29" />
                <f:selectItem itemValue = "30" itemLabel = "30" />
                <f:selectItem itemValue = "31" itemLabel = "31" />
            </h:selectOneMenu> 
            <!--Month-->
            Month:
            <h:selectOneMenu value = "#{reservationDrop.rMonth}">
                <f:selectItem itemValue = "1" itemLabel = "January" />
                <f:selectItem itemValue = "2" itemLabel = "February" />
                <f:selectItem itemValue = "3" itemLabel = "March" />
                <f:selectItem itemValue = "4" itemLabel = "April" />
                <f:selectItem itemValue = "5" itemLabel = "May" />
                <f:selectItem itemValue = "6" itemLabel = "June" />
                <f:selectItem itemValue = "7" itemLabel = "July" />
                <f:selectItem itemValue = "8" itemLabel = "August" />
                <f:selectItem itemValue = "9" itemLabel = "Sepember" />
                <f:selectItem itemValue = "10" itemLabel = "October" />
                <f:selectItem itemValue = "11" itemLabel = "November" />
                <f:selectItem itemValue = "12" itemLabel = "December" />
            </h:selectOneMenu> 
            <!--Year-->
            Year:
            <h:selectOneMenu value = "#{reservationDrop.rYear}">
                <f:selectItem itemValue = "2015" itemLabel = "2015" />
                <f:selectItem itemValue = "2016" itemLabel = "2016" />
                <f:selectItem itemValue = "2017" itemLabel = "2017" />
            </h:selectOneMenu> <br/>
            <!--Time of reservation-->
            <p><b>Select a time</b></p>
            <!--Hour-->
            Hour:
            <h:selectOneMenu value = "#{reservationDrop.rHour}">
                <f:selectItem itemValue = "1" itemLabel = "1" />
                <f:selectItem itemValue = "2" itemLabel = "2" />
                <f:selectItem itemValue = "3" itemLabel = "3" />
                <f:selectItem itemValue = "4" itemLabel = "4" />
                <f:selectItem itemValue = "5" itemLabel = "5" />
                <f:selectItem itemValue = "6" itemLabel = "6" />
                <f:selectItem itemValue = "7" itemLabel = "7" />
                <f:selectItem itemValue = "8" itemLabel = "8" />
                <f:selectItem itemValue = "9" itemLabel = "9" />
                <f:selectItem itemValue = "10" itemLabel = "10" />
                <f:selectItem itemValue = "11" itemLabel = "11" />
                <f:selectItem itemValue = "12" itemLabel = "12" />
            </h:selectOneMenu>
            <!--Minutes-->
            Minute:
            <h:selectOneMenu value = "#{reservationDrop.rMinute}">
                <f:selectItem itemValue = "00" itemLabel = "00" />
                <f:selectItem itemValue = "15" itemLabel = "15" />
                <f:selectItem itemValue = "30" itemLabel = "30" />
                <f:selectItem itemValue = "45" itemLabel = "45" />
            </h:selectOneMenu>
            <!--AM or PM-->
            <h:selectOneMenu value = "#{reservationDrop.ampm}" >
                <f:selectItem itemValue = "AM" itemLabel = "AM" />
                <f:selectItem itemValue = "PM" itemLabel = "PM" />
            </h:selectOneMenu> <br/> <br/>
            <!--Submit product selection button-->
            <h:commandButton value = "Update" type = "submit"
                             action = "DropUpdateReview.xhtml" />
          </h:form>
        </div>
    </h:body>
</html>

CS416/GoGoLimo/FinalProject/web/DropUpdateReview.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html 
    xmlns="http://www.w3.org/1999/xhtml"  
    xmlns:h="http://java.sun.com/jsf/html"  
    xmlns:f="http://java.sun.com/jsf/core">  
    <h:head>
      <title>GoGo Limo</title>
      <style type="text/css">
        h2 {color: white; background-color: #1db140}
      </style>
      <link href="main.css" rel="stylesheet" type="text/css" />
    </h:head>
    
    <h:body>
      <div id="outer">
        <h1>
          <a href="Login.xhtml">
            <h:graphicImage url="/images/LimoLogo.jpg" alt="GoGo Limo"/>
          </a>
        </h1>
      </div>

      <div id="inner">
        <h2>Changes made to Drop off Reservation</h2>
        Thank you. The following changes have been made...
        
        <h2>New drop off date:</h2>
        <p><h:outputText value = "#{reservationDrop.toString()}" /><br/></p> 
        <p><h:outputText value = "#{reservationDrop.idString()}" /><br/></p>
        <p><h:outputLink value="Navigation01.xhtml">Return to Navigation Screen when Ready</h:outputLink></p>
      </div>
    </h:body>
</html>

CS416/GoGoLimo/FinalProject/web/PickConfirm.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        <title>GoGo Limo</title>
        <style type="text/css">
        h2 {color: white; background-color: #1db140}
        </style>
        <link href="main.css" rel="stylesheet" type="text/css" />
    </h:head>
    <h:body>
       <div id="outer">
           <h1>
               <a href="Login.xhtml">
                   <h:graphicImage url="/images/LimoLogo.jpg" alt="GoGo Limo"/>
               </a>
           </h1>
       </div>
 
      <div id="inner"> 
        <h2>Thank you for your order</h2>
        <p> Customer Name: <h:outputText value="#{reservationPickUp.firstName} #{reservationPickUp.lastName}"/><br/>
            Customer Email: <h:outputText value="#{reservationPickUp.email}"/><br/></p>
        <p><h:outputText value="#{reservationPickUp.toString()}"/> <br/></p>
        <p><h:outputText value="#{reservationPickUp.idString()}"/> </p>
        <p><h:outputLink value="Navigation01.xhtml">Return to Navigation Screen</h:outputLink></p>
      </div>
    </h:body>    
</html>

CS416/GoGoLimo/FinalProject/web/PickSearch.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
       <title>GoGo Limo</title>
        <style type="text/css">
          h2 {color: white; background-color: #1db140}
        </style>
        <link href="main.css" rel="stylesheet" type="text/css" />
    </h:head>
    
    <h:body>
      <div id="outer">
          <h1>
              <a href="Login.xhtml">
                  <h:graphicImage url="/images/LimoLogo.jpg" alt="GoGo Limo"/>
              </a>
          </h1>
      </div>
      <div id="inner">            
      <h2>Reservation Pick Up Info Search</h2>
      <h:form>
        <h:panelGrid columns="2">
          <h:outputText value="Confirm Email "/>
          <h:inputText id="email" value="#{reservationPickUp.email}">
          <f:ajax event="keyup" execute="last" render="datatable"/>
        </h:inputText>
      </h:panelGrid><br/>
    
        <h:dataTable id="datatable" value="#{reservePickBean.matchingEmail}"
                     var="item" border="3" cellpadding="2" cellspacing="2">
            <h:column>
                <f:facet name="header">
                  <h:outputText value="Email"/>
                </f:facet> 
                <h:outputText value="#{item.email}"></h:outputText>
            </h:column>

            <h:column>
                <f:facet name="header">
                    <h:outputText value=" - - - - - Reservation Information - - - - - " />
                </f:facet> 
                <h:outputText value="#{item.toString()}" ></h:outputText>
            </h:column>

            <h:column>
                <f:facet name="header">
                  <h:outputText value="Pick-up ID" />
                </f:facet>
                <h:outputText value="#{item.id}" ></h:outputText>
            </h:column>
        </h:dataTable>
      </h:form>
    </div>
        
    <h3>Make Changes to Pick up Schedule</h3>
      <table>  
        <tr>  
          <td><h:outputLink value="PickDelete.xhtml"> Delete a pick up Reservation </h:outputLink></td>
          <td></td>
          <td><h:outputLink value="PickUpdate.xhtml"> Update a pick up Reservation </h:outputLink></td>  
        </tr>  
      </table>
    </h:body>
</html>